/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTodosRouteImport } from './routes/api/todos'
import { Route as appLoginRouteImport } from './routes/(app)/login'
import { Route as appAuthedRouteRouteImport } from './routes/(app)/_authed/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as appAuthedMyTodosRouteImport } from './routes/(app)/_authed/my-todos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodosRoute = ApiTodosRouteImport.update({
  id: '/api/todos',
  path: '/api/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const appLoginRoute = appLoginRouteImport.update({
  id: '/(app)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appAuthedRouteRoute = appAuthedRouteRouteImport.update({
  id: '/(app)/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appAuthedMyTodosRoute = appAuthedMyTodosRouteImport.update({
  id: '/my-todos',
  path: '/my-todos',
  getParentRoute: () => appAuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof appLoginRoute
  '/api/todos': typeof ApiTodosRoute
  '/my-todos': typeof appAuthedMyTodosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof appLoginRoute
  '/api/todos': typeof ApiTodosRoute
  '/my-todos': typeof appAuthedMyTodosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/_authed': typeof appAuthedRouteRouteWithChildren
  '/(app)/login': typeof appLoginRoute
  '/api/todos': typeof ApiTodosRoute
  '/(app)/_authed/my-todos': typeof appAuthedMyTodosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/api/todos' | '/my-todos' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/api/todos' | '/my-todos' | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/(app)/_authed'
    | '/(app)/login'
    | '/api/todos'
    | '/(app)/_authed/my-todos'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appAuthedRouteRoute: typeof appAuthedRouteRouteWithChildren
  appLoginRoute: typeof appLoginRoute
  ApiTodosRoute: typeof ApiTodosRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/todos': {
      id: '/api/todos'
      path: '/api/todos'
      fullPath: '/api/todos'
      preLoaderRoute: typeof ApiTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/login': {
      id: '/(app)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof appLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_authed': {
      id: '/(app)/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_authed/my-todos': {
      id: '/(app)/_authed/my-todos'
      path: '/my-todos'
      fullPath: '/my-todos'
      preLoaderRoute: typeof appAuthedMyTodosRouteImport
      parentRoute: typeof appAuthedRouteRoute
    }
  }
}

interface appAuthedRouteRouteChildren {
  appAuthedMyTodosRoute: typeof appAuthedMyTodosRoute
}

const appAuthedRouteRouteChildren: appAuthedRouteRouteChildren = {
  appAuthedMyTodosRoute: appAuthedMyTodosRoute,
}

const appAuthedRouteRouteWithChildren = appAuthedRouteRoute._addFileChildren(
  appAuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appAuthedRouteRoute: appAuthedRouteRouteWithChildren,
  appLoginRoute: appLoginRoute,
  ApiTodosRoute: ApiTodosRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
